### ISSUE TITLE
`Directory not empty` when installing std lib

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noirup#10]
# Description

## Aim

1. Runs `noirup` with an existing `nargo` installation
2. Installation overwrites both `nargo` and the standard library with new versions

## Bug

```
noirup % sudo bash noirup
noirup: installing nargo (latest stable)
noirup: downloading latest nargo to '/Users/s/.nargo/bin'
########################################################################################################################################## 100.0%
noirup: installing noir-lang/std lib to '/Users/s/Library/Application Support'
mv: rename /Users/s/.nargo/bin/noir-lang to /Users/s/Library/Application Support/noir-lang: Directory not empty
noirup: command failed: mv /Users/s/.nargo/bin/noir-lang /Users/s/Library/Application Support
```

# To reproduce

1. `git clone https://github.com/noir-lang/noirup.git`
2. `cd noirup`
3. `sudo bash noirup`
4. `sudo bash noirup` (rerun after first installation)

# Additional context

Issue lies with the directory discrepancy in the following lines of the script:
```bash
ensure rm -rf "$CONFIG_DIR/noir-lang/std"
```
```bash
ensure mv "$NARGO_BIN_DIR/noir-lang" "$CONFIG_DIR"
```

**Comment by phated** [comment]
I'm wondering if this is actually an issue with `sudo bash` because I tested installing and overwriting a lot of versions yesterday and everything worked. 🤔

**Comment by Globallager** [comment]
Ah indeed. I was confused with steps to run and should have run things in this order instead:
1. `git clone https://github.com/noir-lang/noirup.git`
2. `cd noirup`
3. `zsh install`
4. `source ~/.zshrc`
5. `noirup`
