### ISSUE TITLE
Improve ergonomics of building from source

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noirup#22]
# Problem

There's currently no way to build a given release from source easily. If I want to compile 0.3.2 then I need to go find the commit hash of this release and do `noirup -c 0x0123456`

# Solution

We should instead allow providing the release version which we want to compile directly.

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by phated** [comment]
@TomAFrench noirup is just using `git checkout` so it should work with an reference, such as `-c v0.3.2`. Does that not work?

**Comment by TomAFrench** [comment]
Yep, I forgot about this when I created this issue.
