### ISSUE TITLE
Install from source fails with "no packages found with binaries or examples"

### ISSUE THREAD

**Issue by spalladino** [noir-lang/noirup#25]
Running `noirup --pr ####` fails with `error: no packages found with binaries or examples` (eg [#1071](https://github.com/noir-lang/noir/pull/1071/commits)). It seems that `--path=crates/nargo` is no longer valid and needs to be changed to `--path=crates/nargo_cli`. The instructions for installation on the noir book should also be updated.

**Comment by phated** [comment]
Note that this change is on the unreleased master branch. If the docs are for 0.3.2, then they are correct. The 0.4.0 docs will need to be updated when 0.4.0 is released.

**Comment by spalladino** [comment]
Not sure if you're referring to the noirup docs or the noir book. The former mentions that you can install any PR through it, and the latter that you can "install the latest version by building the project directly from the master branch" (though, to be fair, it mentions that "this may not work as expected").

**Comment by phated** [comment]
Building from source should tell users to check out the same tag that the versioned docs are documenting, but that's a separate issue to this.
