### ISSUE TITLE
Running `noirup` doesn't checkout latest commit when nargo was already installed

### ISSUE THREAD

**Issue by benesjan** [noir-lang/noirup#31]
### Aim

I wanted to get latest version of `nargo` by running `noirup --branch aztec3-hacky` and it didn't checkout the latest commit but instead used an older one I already had checked out.

### Expected Behavior

`noirup` should checkout the latest commit.

### Bug

`noirup` does not checkout latest commit when a version from the same branch is already installed.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Additional Context

I worked around the issue by first running `noirup --branch master` followed by `noirup --branch aztec3-hacky`.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
I'm not sure this is correct. We always fetch the most recent commit of the specified branch and check it out. For this to occur git would have to either fail to update the remote or checkout the wrong commit.

https://github.com/noir-lang/noirup/blob/82f68ffd1f0bcf1009db917df25482bf7e8b2650/noirup#L139-L147

See matching lines in foundryup:

https://github.com/foundry-rs/foundry/blob/626bef3b7f062f0e9662689119ad875504e8cbad/foundryup/foundryup#L195-L204

**Comment by benesjan** [comment]
That was my experience yesterday with noirup but it's possible it could have been github connection issue.

BTW I've just noticed that the noirup command ignores "--version" option.
<img width="688" alt="image" src="https://github.com/noir-lang/noirup/assets/13470840/ce31b3ba-c30c-4e49-b3c4-8a50b76e4b81">

Feel free to close the issue if you think it's not worth investigating.

**Comment by kobyhallx** [comment]
noirup's mission to manage git repository is limited to best effort. We won't be supporting it properly going forward. Please use regular git/build workflow.
