### ISSUE TITLE
Proxy Settings and Root Certificate (pem) file settings

### ISSUE THREAD

**Issue by brianblank** [noir-lang/noirup#36]
### Problem

I am behind a corporate firewall and need to configure nargo to point to an authenticated proxy server and use a specific .pem root certificate file.  Those settings don't appear to be available for nargo.  Without allowing this configuration, I am unable to leverage nargo behind a corporate firewall as it requires downloading /MAIN%20IGNITION/sealed/transcript00.dat and other files.

As a temporary solution, can you confirm where the files are stored once downloaded?  I may be able to manually download the required files using a web browser that is correctly configured and then manually copying the files to where they belong.

I am currently using version 0.7.1 (not sure if this is already addressed in a later version)

### Happy Case

A solution from Rust (using cargo) is to configure the ~/.cargo/config.toml file with following:
[net]
git-fetch-with-cli=true
[http]
proxy="http://UserName:Password@pathToProxyServer:portOfProxyServer/"
cainfo="/pathToCorporateRootCertificate/file.pem"

Note that even with Rust Cargo file, the username/password authentication is not currently working, but this is ideally how it should work.

### Would you like to submit a PR for this Issue?

No

### Support Needs

As a temporary solution, can you confirm where the files are stored once downloaded?  I may be able to manually download the required files using a web browser that is correctly configured and then manually copying the files to where they belong.

**Comment by Savio-Sou** [comment]
Hi there, thanks for creating the issue.
May I know which OS are you on?

**Comment by brianblank** [comment]
I use multiple OS, but it occurs regardless of which OS I am using.  It needs to support an authenticated proxy server so that it can download the files it needs behind corporate proxy servers.

Here is a similar issue with Rust with a patch and other work arounds: https://github.com/rust-lang/cargo/issues/7330
Note that the latest version of Rust supports non-authenticated proxy servers, but claims to support authenticated proxy servers with the patch in the above thread (I haven't tested it).  Noir doesn't support any proxy servers (both authenticated or non-authenticated).

I'm sharing the rust details as I am aware Noir is written in Rust, so maybe you can take a similar approach?

**Comment by Savio-Sou** [comment]
Thanks, asking just to make sure we can find you the local path for storing `transcrip00.dat` for a quick unblock 🙌

If you're on macOS, the path would be `~/.nargo/backends/acvm-backend-barretenberg/transcript00.dat`.

> so maybe you can take a similar approach

Grateful for your insights shared, that could be an approach yes.

Anyone reading that's interested to take this up, do comment below. I'll check if the core team has the bandwidth in parallel.

**Comment by TomAFrench** [comment]
The transcript is downloaded by the backend so this is not under Noir's control I'm afraid.
