### ISSUE TITLE
Add support for `1.0.0-beta.n` releases

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noirup#43]
### Problem

Following https://github.com/noir-lang/noir/issues/6433, Noir releases are now renamed to the new format of **1.0.0-beta.n** (i.e. 1.0.0-beta.0, 1.0.0-beta.1...) which noirup currently does not yet support the fetching and installation of them.

### Happy Case

Update the script to support the new Noir release naming, specifically:

1. Running `noirup` should fetch the latest 0.x.y **or 1.0.0-beta.n** stable release, whichever is latest
2. Running `noirup -v ...` / `noirup --version ...` should fetch the corresponding 0.x.y **or 1.0.0-beta.n** release, e.g. `noirup -v 1.0.0-beta.0` should fetch 1.0.0-beta.0

### Project Impact

Blocker

### Blocker Context

Required before announcing 1.0.0-beta.n on socials

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Have you tested this? `noirup -v 1.0.0-beta.0` works fine.
